spring:
  application:
    name: Hermes

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: hermes-fraud-detector
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR